### ISSUE TITLE
All Tailor records returned, no matter the query

### ISSUE THREAD

**Issue by chocolata** [OFFLINE-GmbH/oc-site-search-plugin#145]
Hi,

I might be making a stupid mistake, but I'm encountering the following issue:

Whenever I search for something, no matter what, all my Tailor Publication records are returned, even when the search query is definitely not present in my Tailor record.

I've got a Blueprint called Publication. Inside there, I've defined the siteSearch configuration:

![image](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/assets/3584586/e691b902-9179-4602-8054-23f7390e6f05)

One thing to note is that the fields I'm searching in reside in a mixin called Content:

![image](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/assets/3584586/a95f2889-340d-4017-b968-df9f7db44c7c)

What am I doing wrong?

**Comment by tobias-kuendig** [comment]
I'd start with debugging the query here: 
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/e4696eb49b9abb1d4721f2f09d61368c580fb9c6/classes/providers/TailorResultsProvider.php#L47-L60

Are your `$searchFields` resolved correctly? What `->where` statements are built (use `->toSql()` instead of `->get()`)

**Comment by tobias-kuendig** [comment]
Thank you for the detailed report, @chocolata! I was able to reproduce the issue, the culprit was indeed the mixin field!

Give `v1.7.17`, it should be fixed now.

**Comment by chocolata** [comment]
Hi @tobias-kuendig, thank you so much for your expert support. This solves it. Thanks so much!

**Comment by chocolata** [comment]
Hi @tobias-kuendig , could it be that the search function still has issues with Taylor records? 

Now the issue with all Taylor records being shown is solved, but for some reason I cannot seem to find specific items that should be found...

For example: these are records that are present in my "Publications" blueprint:

![image](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/assets/3584586/5f256113-1bb7-478b-a36d-8c2ce337610f)

If I search for "RSV" I can find the top one.

![image](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/assets/3584586/d88c5138-3394-4cb9-8997-cb716992fe60)

If I search for "icterius", no results are returned.

![image](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/assets/3584586/d7473584-7c4a-4763-b8ca-f16c2fa651bf)

This is what my search page looks like:

```
title = "Search"
url = "/search"
layout = "default"
is_hidden = 0

[searchResults]
resultsPerPage = 20
showProviderBadge = 1
noResultsMessage = "We could not find anything that matches your keyword. Please try another search term."
visitPageMessage = "Read more"
==

<section class="c-bg">
    <div class="contain">
        <div class="c-intro">
            <div class="c-intro__text">
                <h1>{{ 'Zoekresultaten voor ":keyword"' | _({keyword: searchResults.query }) }}</h1>
            </div>
        </div>

        <div class="">
            {% set results = searchResults.results %}
            {% if results | length %}
            <div class="c-raster">
                {% for result in results %}
                    {% partial 'common/card' card_view=0 post=result hide_published_date=1 url=result.url %}
                {% endfor %}
            </div>
            {% else %}
                {% partial searchResults ~ '::no-results.htm' %}
            {% endif %}
            {% partial searchResults ~ '::pagination.htm' results = results %}
        </div>
        
    </div>
</section>

```

This is what my Publications blueprint looks like:

```
uuid: 8b7cd3ce-b225-4bcb-a11c-85805273e2cd
handle: Library\Publication
type: stream
name: Publicaties
drafts: false
multisite: true

primaryNavigation:
    label: Publicaties
    icon: icon-bookmark
    order: 130

navigation:
    icon: icon-bookmark
    parent: Library\Publication
    order: 10

fields:
    is_premium:
        tab: Manage
        type: switch
        label: Premium / Members only
        comment: Markeren als enkel beschikbaar voor betalende leden
    _content:
        tab: Manage
        type: mixin
        source: Content
    categories:
        tab: Manage
        label: Categorieën
        commentAbove: 'Kies de categorieën waartoe deze publicatie behoort'
        type: entries
        source: Library\Category
    _meta:
        tab: Meta
        type: mixin
        source: Meta

siteSearch:
    providerBadge: 'Publicatie' # Display this beside each search result.

    pageName: 'library/publication'   # Filename of the target CMS page, used to build links.
    urlParams:             # Given a page URL: /target-cms-page/:slug/:something
        slug: $slug          # Use the value of the "slug" field, since it is prefixed with a "$"
        # the output is: /target-cms-page/slug-field-value/else

    searchFields:
        - title
        - content
        - excerpt
        - author
        - author_details


    #thumbFrom: featured_images[0]       # Use the `image` field as thumbnail. Must be a fileupload.
    resultFields:
        title: title       # Use the "title" field as the search result title
        text: content  # Use the "description" field as the search result text


```

This is the content mixin: 

```
uuid: 955fda63-82dd-4cf1-9b66-b671cef21626
handle: Content
type: mixin
name: Content

fields:
    content:
        tab: Edit
        label: Inhoud
        type: richeditor
        span: adaptive
    excerpt:
        tab: Manage
        label: Uittreksel
        commentAbove: 'Deze tekst wordt weergegeven in lijstweergaven, in plaats van een ingekorte versie van de content'
        type: textarea
    files:
        tab: Manage
        label: Bestanden
        type: fileupload
        mode: file
    featured_images:
        tab: Manage
        label: Afbeeldingen
        commentAbove: De eerste afbeelding wordt gebruikt als cover
        type: fileupload
        mode: image
    highlighted:
        tab: Manage
        label: Uitgelicht
        type: switch
        comment: Als dit aangevinkt is, krijgt het artikel een achtergrondkleur in lijstweergaven
    author:
        label: Auteur of organiserende firma
        commentAbove: Kort label over de organisatie die dit event organiseert of deze publicatie gepubliceerd heeft
        type: text
        tab: Manage
        span: full
    author_details:
        label: Meer info over de auteur of organiserende firma
        type: textarea
        tab: Manage
        span: full


```
I'm using October CMS v3.5.15 in combination with OFFLINE SiteSearch v1.7.17.

I am encountering this issue across multiple sites unfortunately... Could you kindly see what is wrong?
