### ISSUE TITLE
Unable to disable Tailor provider

### ISSUE THREAD

**Issue by envas** [OFFLINE-GmbH/oc-site-search-plugin#148]
In version 1.7.20, a new settings option allows users to turn the Tailor search provider on/off. However, it does not work; even when disabled, the Tailor provider delivers results. I checked the source code and did not find the usage of the `isEnabled()` function. In the CMS provider, the search starts with the code:

```
        if ( ! $this->isEnabled()) {
            return $this;
        }
```

The Tailor provider needs the test too! IMO, it's a bug.

**Comment by tobias-kuendig** [comment]
Thanks, looks like the setting was never properly implemented. 

This is fixed in v1.7.21

**Comment by chocolata** [comment]
Hi, could it be that there is an issue with this setting? For the life of me I can't seem to be able to get my Tailor records in my search results, no matter if I switch this on or off...

My blueprint looks like this. Could you help me out?

```
uuid: 8b7cd3ce-b225-4bcb-a11c-85805273e2cd
handle: Library\Publication
type: stream
name: Publications
drafts: false
multisite: false

primaryNavigation:
    label: Publicaties
    icon: icon-bookmark
    order: 130

navigation:
    icon: icon-bookmark
    parent: Library\Publication
    order: 10

fields:
    is_premium:
        tab: Manage
        type: switch
        label: Premium / Members only
        comment: Markeren als enkel beschikbaar voor betalende leden
    _content:
        tab: Manage
        type: mixin
        source: Content
    categories:
        tab: Manage
        label: Categorieën
        commentAbove: 'Kies de categorieën waartoe deze publicatie behoort'
        type: entries
        source: Library\Category
    _meta:
        tab: Meta
        type: mixin
        source: Meta

siteSearch:
    providerBadge: 'Publication' # Display this beside each search result.

    pageName: 'library/publication'   # Filename of the target CMS page, used to build links.
    urlParams:             # Given a page URL: /target-cms-page/:slug/:something
        slug: $slug          # Use the value of the "slug" field, since it is prefixed with a "$"
        # the output is: /target-cms-page/slug-field-value/else

    searchFields:
        - title
        - content
        - excerpt
        - author
        - author_details

    thumbFrom: featured_images[0]       # Use the `image` field as thumbnail. Must be a fileupload.
    resultFields:
        title: title       # Use the "title" field as the search result title
        text: content  # Use the "description" field as the search result text
```
